syntax = "proto3";

                 package category;
service CategoryService {
 rpc createCategory (CategoryCreateInput) returns (Category) {}
rpc categories (findManyParams) returns (stream Category) {}
rpc category (CategoryWhereUniqueInput) returns (Category) {}
rpc updateCategory (CategoryUpdateInput) returns (Category) {}
rpc deleteCategory (CategoryWhereUniqueInput) returns (Category) {} 
 }
message CategoryCreateInput {
string createdAt = 1;
string id = 2;
string ownerId = 3;
string updatedAt = 4;
};
message Category {
string createdAt = 1;
string id = 2;
string ownerId = 3;
string updatedAt = 4;
};
message CategoryWhereUniqueInput {
string createdAt = 1;
string id = 2;
string ownerId = 3;
string updatedAt = 4;
};
message CategoryUpdateInput {
string createdAt = 1;
string id = 2;
string ownerId = 3;
string updatedAt = 4;
};
message findManyParams {

};