/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SocialNetwork } from "./SocialNetwork";
import { SocialNetworkCountArgs } from "./SocialNetworkCountArgs";
import { SocialNetworkFindManyArgs } from "./SocialNetworkFindManyArgs";
import { SocialNetworkFindUniqueArgs } from "./SocialNetworkFindUniqueArgs";
import { DeleteSocialNetworkArgs } from "./DeleteSocialNetworkArgs";
import { SocialNetworkService } from "../socialNetwork.service";
@graphql.Resolver(() => SocialNetwork)
export class SocialNetworkResolverBase {
  constructor(protected readonly service: SocialNetworkService) {}

  async _socialNetworksMeta(
    @graphql.Args() args: SocialNetworkCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SocialNetwork])
  async socialNetworks(
    @graphql.Args() args: SocialNetworkFindManyArgs
  ): Promise<SocialNetwork[]> {
    return this.service.socialNetworks(args);
  }

  @graphql.Query(() => SocialNetwork, { nullable: true })
  async socialNetwork(
    @graphql.Args() args: SocialNetworkFindUniqueArgs
  ): Promise<SocialNetwork | null> {
    const result = await this.service.socialNetwork(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SocialNetwork)
  async deleteSocialNetwork(
    @graphql.Args() args: DeleteSocialNetworkArgs
  ): Promise<SocialNetwork | null> {
    try {
      return await this.service.deleteSocialNetwork(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
