/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, SocialNetwork as PrismaSocialNetwork } from "@prisma/client";

export class SocialNetworkServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SocialNetworkCountArgs, "select">
  ): Promise<number> {
    return this.prisma.socialNetwork.count(args);
  }

  async socialNetworks(
    args: Prisma.SocialNetworkFindManyArgs
  ): Promise<PrismaSocialNetwork[]> {
    return this.prisma.socialNetwork.findMany(args);
  }
  async socialNetwork(
    args: Prisma.SocialNetworkFindUniqueArgs
  ): Promise<PrismaSocialNetwork | null> {
    return this.prisma.socialNetwork.findUnique(args);
  }
  async createSocialNetwork(
    args: Prisma.SocialNetworkCreateArgs
  ): Promise<PrismaSocialNetwork> {
    return this.prisma.socialNetwork.create(args);
  }
  async updateSocialNetwork(
    args: Prisma.SocialNetworkUpdateArgs
  ): Promise<PrismaSocialNetwork> {
    return this.prisma.socialNetwork.update(args);
  }
  async deleteSocialNetwork(
    args: Prisma.SocialNetworkDeleteArgs
  ): Promise<PrismaSocialNetwork> {
    return this.prisma.socialNetwork.delete(args);
  }
}
