/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SocialNetworkService } from "../socialNetwork.service";
import { SocialNetworkCreateInput } from "./SocialNetworkCreateInput";
import { SocialNetwork } from "./SocialNetwork";
import { SocialNetworkFindManyArgs } from "./SocialNetworkFindManyArgs";
import { SocialNetworkWhereUniqueInput } from "./SocialNetworkWhereUniqueInput";
import { SocialNetworkUpdateInput } from "./SocialNetworkUpdateInput";

export class SocialNetworkControllerBase {
  constructor(protected readonly service: SocialNetworkService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SocialNetwork })
  async createSocialNetwork(
    @common.Body() data: SocialNetworkCreateInput
  ): Promise<SocialNetwork> {
    return await this.service.createSocialNetwork({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SocialNetwork] })
  @ApiNestedQuery(SocialNetworkFindManyArgs)
  async socialNetworks(
    @common.Req() request: Request
  ): Promise<SocialNetwork[]> {
    const args = plainToClass(SocialNetworkFindManyArgs, request.query);
    return this.service.socialNetworks({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SocialNetwork })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async socialNetwork(
    @common.Param() params: SocialNetworkWhereUniqueInput
  ): Promise<SocialNetwork | null> {
    const result = await this.service.socialNetwork({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SocialNetwork })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSocialNetwork(
    @common.Param() params: SocialNetworkWhereUniqueInput,
    @common.Body() data: SocialNetworkUpdateInput
  ): Promise<SocialNetwork | null> {
    try {
      return await this.service.updateSocialNetwork({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SocialNetwork })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSocialNetwork(
    @common.Param() params: SocialNetworkWhereUniqueInput
  ): Promise<SocialNetwork | null> {
    try {
      return await this.service.deleteSocialNetwork({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
