/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Description } from "./Description";
import { DescriptionCountArgs } from "./DescriptionCountArgs";
import { DescriptionFindManyArgs } from "./DescriptionFindManyArgs";
import { DescriptionFindUniqueArgs } from "./DescriptionFindUniqueArgs";
import { DeleteDescriptionArgs } from "./DeleteDescriptionArgs";
import { DescriptionService } from "../description.service";
@graphql.Resolver(() => Description)
export class DescriptionResolverBase {
  constructor(protected readonly service: DescriptionService) {}

  async _descriptionsMeta(
    @graphql.Args() args: DescriptionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Description])
  async descriptions(
    @graphql.Args() args: DescriptionFindManyArgs
  ): Promise<Description[]> {
    return this.service.descriptions(args);
  }

  @graphql.Query(() => Description, { nullable: true })
  async description(
    @graphql.Args() args: DescriptionFindUniqueArgs
  ): Promise<Description | null> {
    const result = await this.service.description(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Description)
  async deleteDescription(
    @graphql.Args() args: DeleteDescriptionArgs
  ): Promise<Description | null> {
    try {
      return await this.service.deleteDescription(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
