/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DescriptionService } from "../description.service";
import { DescriptionCreateInput } from "./DescriptionCreateInput";
import { Description } from "./Description";
import { DescriptionFindManyArgs } from "./DescriptionFindManyArgs";
import { DescriptionWhereUniqueInput } from "./DescriptionWhereUniqueInput";
import { DescriptionUpdateInput } from "./DescriptionUpdateInput";

export class DescriptionControllerBase {
  constructor(protected readonly service: DescriptionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Description })
  async createDescription(
    @common.Body() data: DescriptionCreateInput
  ): Promise<Description> {
    return await this.service.createDescription({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Description] })
  @ApiNestedQuery(DescriptionFindManyArgs)
  async descriptions(@common.Req() request: Request): Promise<Description[]> {
    const args = plainToClass(DescriptionFindManyArgs, request.query);
    return this.service.descriptions({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Description })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async description(
    @common.Param() params: DescriptionWhereUniqueInput
  ): Promise<Description | null> {
    const result = await this.service.description({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Description })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDescription(
    @common.Param() params: DescriptionWhereUniqueInput,
    @common.Body() data: DescriptionUpdateInput
  ): Promise<Description | null> {
    try {
      return await this.service.updateDescription({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Description })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDescription(
    @common.Param() params: DescriptionWhereUniqueInput
  ): Promise<Description | null> {
    try {
      return await this.service.deleteDescription({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
