/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Description as PrismaDescription } from "@prisma/client";

export class DescriptionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DescriptionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.description.count(args);
  }

  async descriptions(
    args: Prisma.DescriptionFindManyArgs
  ): Promise<PrismaDescription[]> {
    return this.prisma.description.findMany(args);
  }
  async description(
    args: Prisma.DescriptionFindUniqueArgs
  ): Promise<PrismaDescription | null> {
    return this.prisma.description.findUnique(args);
  }
  async createDescription(
    args: Prisma.DescriptionCreateArgs
  ): Promise<PrismaDescription> {
    return this.prisma.description.create(args);
  }
  async updateDescription(
    args: Prisma.DescriptionUpdateArgs
  ): Promise<PrismaDescription> {
    return this.prisma.description.update(args);
  }
  async deleteDescription(
    args: Prisma.DescriptionDeleteArgs
  ): Promise<PrismaDescription> {
    return this.prisma.description.delete(args);
  }
}
