/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MarketplaceDiscountService } from "../marketplaceDiscount.service";
import { MarketplaceDiscountCreateInput } from "./MarketplaceDiscountCreateInput";
import { MarketplaceDiscount } from "./MarketplaceDiscount";
import { MarketplaceDiscountFindManyArgs } from "./MarketplaceDiscountFindManyArgs";
import { MarketplaceDiscountWhereUniqueInput } from "./MarketplaceDiscountWhereUniqueInput";
import { MarketplaceDiscountUpdateInput } from "./MarketplaceDiscountUpdateInput";

export class MarketplaceDiscountControllerBase {
  constructor(protected readonly service: MarketplaceDiscountService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MarketplaceDiscount })
  async createMarketplaceDiscount(
    @common.Body() data: MarketplaceDiscountCreateInput
  ): Promise<MarketplaceDiscount> {
    return await this.service.createMarketplaceDiscount({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [MarketplaceDiscount] })
  @ApiNestedQuery(MarketplaceDiscountFindManyArgs)
  async marketplaceDiscounts(
    @common.Req() request: Request
  ): Promise<MarketplaceDiscount[]> {
    const args = plainToClass(MarketplaceDiscountFindManyArgs, request.query);
    return this.service.marketplaceDiscounts({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MarketplaceDiscount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async marketplaceDiscount(
    @common.Param() params: MarketplaceDiscountWhereUniqueInput
  ): Promise<MarketplaceDiscount | null> {
    const result = await this.service.marketplaceDiscount({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MarketplaceDiscount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMarketplaceDiscount(
    @common.Param() params: MarketplaceDiscountWhereUniqueInput,
    @common.Body() data: MarketplaceDiscountUpdateInput
  ): Promise<MarketplaceDiscount | null> {
    try {
      return await this.service.updateMarketplaceDiscount({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MarketplaceDiscount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMarketplaceDiscount(
    @common.Param() params: MarketplaceDiscountWhereUniqueInput
  ): Promise<MarketplaceDiscount | null> {
    try {
      return await this.service.deleteMarketplaceDiscount({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
