/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  MarketplaceDiscount as PrismaMarketplaceDiscount,
} from "@prisma/client";

export class MarketplaceDiscountServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.MarketplaceDiscountCountArgs, "select">
  ): Promise<number> {
    return this.prisma.marketplaceDiscount.count(args);
  }

  async marketplaceDiscounts(
    args: Prisma.MarketplaceDiscountFindManyArgs
  ): Promise<PrismaMarketplaceDiscount[]> {
    return this.prisma.marketplaceDiscount.findMany(args);
  }
  async marketplaceDiscount(
    args: Prisma.MarketplaceDiscountFindUniqueArgs
  ): Promise<PrismaMarketplaceDiscount | null> {
    return this.prisma.marketplaceDiscount.findUnique(args);
  }
  async createMarketplaceDiscount(
    args: Prisma.MarketplaceDiscountCreateArgs
  ): Promise<PrismaMarketplaceDiscount> {
    return this.prisma.marketplaceDiscount.create(args);
  }
  async updateMarketplaceDiscount(
    args: Prisma.MarketplaceDiscountUpdateArgs
  ): Promise<PrismaMarketplaceDiscount> {
    return this.prisma.marketplaceDiscount.update(args);
  }
  async deleteMarketplaceDiscount(
    args: Prisma.MarketplaceDiscountDeleteArgs
  ): Promise<PrismaMarketplaceDiscount> {
    return this.prisma.marketplaceDiscount.delete(args);
  }
}
