/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { MarketplaceDiscount } from "./MarketplaceDiscount";
import { MarketplaceDiscountCountArgs } from "./MarketplaceDiscountCountArgs";
import { MarketplaceDiscountFindManyArgs } from "./MarketplaceDiscountFindManyArgs";
import { MarketplaceDiscountFindUniqueArgs } from "./MarketplaceDiscountFindUniqueArgs";
import { DeleteMarketplaceDiscountArgs } from "./DeleteMarketplaceDiscountArgs";
import { MarketplaceDiscountService } from "../marketplaceDiscount.service";
@graphql.Resolver(() => MarketplaceDiscount)
export class MarketplaceDiscountResolverBase {
  constructor(protected readonly service: MarketplaceDiscountService) {}

  async _marketplaceDiscountsMeta(
    @graphql.Args() args: MarketplaceDiscountCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [MarketplaceDiscount])
  async marketplaceDiscounts(
    @graphql.Args() args: MarketplaceDiscountFindManyArgs
  ): Promise<MarketplaceDiscount[]> {
    return this.service.marketplaceDiscounts(args);
  }

  @graphql.Query(() => MarketplaceDiscount, { nullable: true })
  async marketplaceDiscount(
    @graphql.Args() args: MarketplaceDiscountFindUniqueArgs
  ): Promise<MarketplaceDiscount | null> {
    const result = await this.service.marketplaceDiscount(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MarketplaceDiscount)
  async deleteMarketplaceDiscount(
    @graphql.Args() args: DeleteMarketplaceDiscountArgs
  ): Promise<MarketplaceDiscount | null> {
    try {
      return await this.service.deleteMarketplaceDiscount(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
