/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ProfitabilityAnalysis as PrismaProfitabilityAnalysis,
} from "@prisma/client";

export class ProfitabilityAnalysisServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ProfitabilityAnalysisCountArgs, "select">
  ): Promise<number> {
    return this.prisma.profitabilityAnalysis.count(args);
  }

  async profitabilityAnalyses(
    args: Prisma.ProfitabilityAnalysisFindManyArgs
  ): Promise<PrismaProfitabilityAnalysis[]> {
    return this.prisma.profitabilityAnalysis.findMany(args);
  }
  async profitabilityAnalysis(
    args: Prisma.ProfitabilityAnalysisFindUniqueArgs
  ): Promise<PrismaProfitabilityAnalysis | null> {
    return this.prisma.profitabilityAnalysis.findUnique(args);
  }
  async createProfitabilityAnalysis(
    args: Prisma.ProfitabilityAnalysisCreateArgs
  ): Promise<PrismaProfitabilityAnalysis> {
    return this.prisma.profitabilityAnalysis.create(args);
  }
  async updateProfitabilityAnalysis(
    args: Prisma.ProfitabilityAnalysisUpdateArgs
  ): Promise<PrismaProfitabilityAnalysis> {
    return this.prisma.profitabilityAnalysis.update(args);
  }
  async deleteProfitabilityAnalysis(
    args: Prisma.ProfitabilityAnalysisDeleteArgs
  ): Promise<PrismaProfitabilityAnalysis> {
    return this.prisma.profitabilityAnalysis.delete(args);
  }
}
