/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProfitabilityAnalysis } from "./ProfitabilityAnalysis";
import { ProfitabilityAnalysisCountArgs } from "./ProfitabilityAnalysisCountArgs";
import { ProfitabilityAnalysisFindManyArgs } from "./ProfitabilityAnalysisFindManyArgs";
import { ProfitabilityAnalysisFindUniqueArgs } from "./ProfitabilityAnalysisFindUniqueArgs";
import { DeleteProfitabilityAnalysisArgs } from "./DeleteProfitabilityAnalysisArgs";
import { ProfitabilityAnalysisService } from "../profitabilityAnalysis.service";
@graphql.Resolver(() => ProfitabilityAnalysis)
export class ProfitabilityAnalysisResolverBase {
  constructor(protected readonly service: ProfitabilityAnalysisService) {}

  async _profitabilityAnalysesMeta(
    @graphql.Args() args: ProfitabilityAnalysisCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProfitabilityAnalysis])
  async profitabilityAnalyses(
    @graphql.Args() args: ProfitabilityAnalysisFindManyArgs
  ): Promise<ProfitabilityAnalysis[]> {
    return this.service.profitabilityAnalyses(args);
  }

  @graphql.Query(() => ProfitabilityAnalysis, { nullable: true })
  async profitabilityAnalysis(
    @graphql.Args() args: ProfitabilityAnalysisFindUniqueArgs
  ): Promise<ProfitabilityAnalysis | null> {
    const result = await this.service.profitabilityAnalysis(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProfitabilityAnalysis)
  async deleteProfitabilityAnalysis(
    @graphql.Args() args: DeleteProfitabilityAnalysisArgs
  ): Promise<ProfitabilityAnalysis | null> {
    try {
      return await this.service.deleteProfitabilityAnalysis(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
