/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PublicationScheduleService } from "../publicationSchedule.service";
import { PublicationScheduleCreateInput } from "./PublicationScheduleCreateInput";
import { PublicationSchedule } from "./PublicationSchedule";
import { PublicationScheduleFindManyArgs } from "./PublicationScheduleFindManyArgs";
import { PublicationScheduleWhereUniqueInput } from "./PublicationScheduleWhereUniqueInput";
import { PublicationScheduleUpdateInput } from "./PublicationScheduleUpdateInput";

export class PublicationScheduleControllerBase {
  constructor(protected readonly service: PublicationScheduleService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PublicationSchedule })
  async createPublicationSchedule(
    @common.Body() data: PublicationScheduleCreateInput
  ): Promise<PublicationSchedule> {
    return await this.service.createPublicationSchedule({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PublicationSchedule] })
  @ApiNestedQuery(PublicationScheduleFindManyArgs)
  async publicationSchedules(
    @common.Req() request: Request
  ): Promise<PublicationSchedule[]> {
    const args = plainToClass(PublicationScheduleFindManyArgs, request.query);
    return this.service.publicationSchedules({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PublicationSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async publicationSchedule(
    @common.Param() params: PublicationScheduleWhereUniqueInput
  ): Promise<PublicationSchedule | null> {
    const result = await this.service.publicationSchedule({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PublicationSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePublicationSchedule(
    @common.Param() params: PublicationScheduleWhereUniqueInput,
    @common.Body() data: PublicationScheduleUpdateInput
  ): Promise<PublicationSchedule | null> {
    try {
      return await this.service.updatePublicationSchedule({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PublicationSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePublicationSchedule(
    @common.Param() params: PublicationScheduleWhereUniqueInput
  ): Promise<PublicationSchedule | null> {
    try {
      return await this.service.deletePublicationSchedule({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
