/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  PublicationSchedule as PrismaPublicationSchedule,
} from "@prisma/client";

export class PublicationScheduleServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PublicationScheduleCountArgs, "select">
  ): Promise<number> {
    return this.prisma.publicationSchedule.count(args);
  }

  async publicationSchedules(
    args: Prisma.PublicationScheduleFindManyArgs
  ): Promise<PrismaPublicationSchedule[]> {
    return this.prisma.publicationSchedule.findMany(args);
  }
  async publicationSchedule(
    args: Prisma.PublicationScheduleFindUniqueArgs
  ): Promise<PrismaPublicationSchedule | null> {
    return this.prisma.publicationSchedule.findUnique(args);
  }
  async createPublicationSchedule(
    args: Prisma.PublicationScheduleCreateArgs
  ): Promise<PrismaPublicationSchedule> {
    return this.prisma.publicationSchedule.create(args);
  }
  async updatePublicationSchedule(
    args: Prisma.PublicationScheduleUpdateArgs
  ): Promise<PrismaPublicationSchedule> {
    return this.prisma.publicationSchedule.update(args);
  }
  async deletePublicationSchedule(
    args: Prisma.PublicationScheduleDeleteArgs
  ): Promise<PrismaPublicationSchedule> {
    return this.prisma.publicationSchedule.delete(args);
  }
}
