/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PublicationSchedule } from "./PublicationSchedule";
import { PublicationScheduleCountArgs } from "./PublicationScheduleCountArgs";
import { PublicationScheduleFindManyArgs } from "./PublicationScheduleFindManyArgs";
import { PublicationScheduleFindUniqueArgs } from "./PublicationScheduleFindUniqueArgs";
import { DeletePublicationScheduleArgs } from "./DeletePublicationScheduleArgs";
import { PublicationScheduleService } from "../publicationSchedule.service";
@graphql.Resolver(() => PublicationSchedule)
export class PublicationScheduleResolverBase {
  constructor(protected readonly service: PublicationScheduleService) {}

  async _publicationSchedulesMeta(
    @graphql.Args() args: PublicationScheduleCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PublicationSchedule])
  async publicationSchedules(
    @graphql.Args() args: PublicationScheduleFindManyArgs
  ): Promise<PublicationSchedule[]> {
    return this.service.publicationSchedules(args);
  }

  @graphql.Query(() => PublicationSchedule, { nullable: true })
  async publicationSchedule(
    @graphql.Args() args: PublicationScheduleFindUniqueArgs
  ): Promise<PublicationSchedule | null> {
    const result = await this.service.publicationSchedule(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PublicationSchedule)
  async deletePublicationSchedule(
    @graphql.Args() args: DeletePublicationScheduleArgs
  ): Promise<PublicationSchedule | null> {
    try {
      return await this.service.deletePublicationSchedule(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
