/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SalePrice as PrismaSalePrice,
  Tenant as PrismaTenant,
} from "@prisma/client";

export class SalePriceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SalePriceCountArgs, "select">
  ): Promise<number> {
    return this.prisma.salePrice.count(args);
  }

  async salePrices(
    args: Prisma.SalePriceFindManyArgs
  ): Promise<PrismaSalePrice[]> {
    return this.prisma.salePrice.findMany(args);
  }
  async salePrice(
    args: Prisma.SalePriceFindUniqueArgs
  ): Promise<PrismaSalePrice | null> {
    return this.prisma.salePrice.findUnique(args);
  }
  async createSalePrice(
    args: Prisma.SalePriceCreateArgs
  ): Promise<PrismaSalePrice> {
    return this.prisma.salePrice.create(args);
  }
  async updateSalePrice(
    args: Prisma.SalePriceUpdateArgs
  ): Promise<PrismaSalePrice> {
    return this.prisma.salePrice.update(args);
  }
  async deleteSalePrice(
    args: Prisma.SalePriceDeleteArgs
  ): Promise<PrismaSalePrice> {
    return this.prisma.salePrice.delete(args);
  }

  async getTenant(parentId: string): Promise<PrismaTenant | null> {
    return this.prisma.salePrice
      .findUnique({
        where: { id: parentId },
      })
      .tenant();
  }
}
