/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SalePriceService } from "../salePrice.service";
import { SalePriceCreateInput } from "./SalePriceCreateInput";
import { SalePrice } from "./SalePrice";
import { SalePriceFindManyArgs } from "./SalePriceFindManyArgs";
import { SalePriceWhereUniqueInput } from "./SalePriceWhereUniqueInput";
import { SalePriceUpdateInput } from "./SalePriceUpdateInput";

export class SalePriceControllerBase {
  constructor(protected readonly service: SalePriceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SalePrice })
  async createSalePrice(
    @common.Body() data: SalePriceCreateInput
  ): Promise<SalePrice> {
    return await this.service.createSalePrice({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SalePrice] })
  @ApiNestedQuery(SalePriceFindManyArgs)
  async salePrices(@common.Req() request: Request): Promise<SalePrice[]> {
    const args = plainToClass(SalePriceFindManyArgs, request.query);
    return this.service.salePrices({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SalePrice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async salePrice(
    @common.Param() params: SalePriceWhereUniqueInput
  ): Promise<SalePrice | null> {
    const result = await this.service.salePrice({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SalePrice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSalePrice(
    @common.Param() params: SalePriceWhereUniqueInput,
    @common.Body() data: SalePriceUpdateInput
  ): Promise<SalePrice | null> {
    try {
      return await this.service.updateSalePrice({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SalePrice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSalePrice(
    @common.Param() params: SalePriceWhereUniqueInput
  ): Promise<SalePrice | null> {
    try {
      return await this.service.deleteSalePrice({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
