/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SalePrice } from "./SalePrice";
import { SalePriceCountArgs } from "./SalePriceCountArgs";
import { SalePriceFindManyArgs } from "./SalePriceFindManyArgs";
import { SalePriceFindUniqueArgs } from "./SalePriceFindUniqueArgs";
import { CreateSalePriceArgs } from "./CreateSalePriceArgs";
import { UpdateSalePriceArgs } from "./UpdateSalePriceArgs";
import { DeleteSalePriceArgs } from "./DeleteSalePriceArgs";
import { Tenant } from "../../tenant/base/Tenant";
import { SalePriceService } from "../salePrice.service";
@graphql.Resolver(() => SalePrice)
export class SalePriceResolverBase {
  constructor(protected readonly service: SalePriceService) {}

  async _salePricesMeta(
    @graphql.Args() args: SalePriceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SalePrice])
  async salePrices(
    @graphql.Args() args: SalePriceFindManyArgs
  ): Promise<SalePrice[]> {
    return this.service.salePrices(args);
  }

  @graphql.Query(() => SalePrice, { nullable: true })
  async salePrice(
    @graphql.Args() args: SalePriceFindUniqueArgs
  ): Promise<SalePrice | null> {
    const result = await this.service.salePrice(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SalePrice)
  async createSalePrice(
    @graphql.Args() args: CreateSalePriceArgs
  ): Promise<SalePrice> {
    return await this.service.createSalePrice({
      ...args,
      data: {
        ...args.data,

        tenant: args.data.tenant
          ? {
              connect: args.data.tenant,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => SalePrice)
  async updateSalePrice(
    @graphql.Args() args: UpdateSalePriceArgs
  ): Promise<SalePrice | null> {
    try {
      return await this.service.updateSalePrice({
        ...args,
        data: {
          ...args.data,

          tenant: args.data.tenant
            ? {
                connect: args.data.tenant,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SalePrice)
  async deleteSalePrice(
    @graphql.Args() args: DeleteSalePriceArgs
  ): Promise<SalePrice | null> {
    try {
      return await this.service.deleteSalePrice(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Tenant, {
    nullable: true,
    name: "tenant",
  })
  async getTenant(@graphql.Parent() parent: SalePrice): Promise<Tenant | null> {
    const result = await this.service.getTenant(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
