/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TenantService } from "../tenant.service";
import { TenantCreateInput } from "./TenantCreateInput";
import { Tenant } from "./Tenant";
import { TenantFindManyArgs } from "./TenantFindManyArgs";
import { TenantWhereUniqueInput } from "./TenantWhereUniqueInput";
import { TenantUpdateInput } from "./TenantUpdateInput";
import { PurchasePriceFindManyArgs } from "../../purchasePrice/base/PurchasePriceFindManyArgs";
import { PurchasePrice } from "../../purchasePrice/base/PurchasePrice";
import { PurchasePriceWhereUniqueInput } from "../../purchasePrice/base/PurchasePriceWhereUniqueInput";
import { SalePriceFindManyArgs } from "../../salePrice/base/SalePriceFindManyArgs";
import { SalePrice } from "../../salePrice/base/SalePrice";
import { SalePriceWhereUniqueInput } from "../../salePrice/base/SalePriceWhereUniqueInput";

export class TenantControllerBase {
  constructor(protected readonly service: TenantService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Tenant })
  async createTenant(@common.Body() data: TenantCreateInput): Promise<Tenant> {
    return await this.service.createTenant({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Tenant] })
  @ApiNestedQuery(TenantFindManyArgs)
  async tenants(@common.Req() request: Request): Promise<Tenant[]> {
    const args = plainToClass(TenantFindManyArgs, request.query);
    return this.service.tenants({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Tenant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async tenant(
    @common.Param() params: TenantWhereUniqueInput
  ): Promise<Tenant | null> {
    const result = await this.service.tenant({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Tenant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTenant(
    @common.Param() params: TenantWhereUniqueInput,
    @common.Body() data: TenantUpdateInput
  ): Promise<Tenant | null> {
    try {
      return await this.service.updateTenant({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Tenant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTenant(
    @common.Param() params: TenantWhereUniqueInput
  ): Promise<Tenant | null> {
    try {
      return await this.service.deleteTenant({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/purchasePrices")
  @ApiNestedQuery(PurchasePriceFindManyArgs)
  async findPurchasePrices(
    @common.Req() request: Request,
    @common.Param() params: TenantWhereUniqueInput
  ): Promise<PurchasePrice[]> {
    const query = plainToClass(PurchasePriceFindManyArgs, request.query);
    const results = await this.service.findPurchasePrices(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        ownerId: true,
        productId: true,

        tenant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/purchasePrices")
  async connectPurchasePrices(
    @common.Param() params: TenantWhereUniqueInput,
    @common.Body() body: PurchasePriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      purchasePrices: {
        connect: body,
      },
    };
    await this.service.updateTenant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/purchasePrices")
  async updatePurchasePrices(
    @common.Param() params: TenantWhereUniqueInput,
    @common.Body() body: PurchasePriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      purchasePrices: {
        set: body,
      },
    };
    await this.service.updateTenant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/purchasePrices")
  async disconnectPurchasePrices(
    @common.Param() params: TenantWhereUniqueInput,
    @common.Body() body: PurchasePriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      purchasePrices: {
        disconnect: body,
      },
    };
    await this.service.updateTenant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/salePrices")
  @ApiNestedQuery(SalePriceFindManyArgs)
  async findSalePrices(
    @common.Req() request: Request,
    @common.Param() params: TenantWhereUniqueInput
  ): Promise<SalePrice[]> {
    const query = plainToClass(SalePriceFindManyArgs, request.query);
    const results = await this.service.findSalePrices(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        ownerId: true,

        tenant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/salePrices")
  async connectSalePrices(
    @common.Param() params: TenantWhereUniqueInput,
    @common.Body() body: SalePriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      salePrices: {
        connect: body,
      },
    };
    await this.service.updateTenant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/salePrices")
  async updateSalePrices(
    @common.Param() params: TenantWhereUniqueInput,
    @common.Body() body: SalePriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      salePrices: {
        set: body,
      },
    };
    await this.service.updateTenant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/salePrices")
  async disconnectSalePrices(
    @common.Param() params: TenantWhereUniqueInput,
    @common.Body() body: SalePriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      salePrices: {
        disconnect: body,
      },
    };
    await this.service.updateTenant({
      where: params,
      data,
      select: { id: true },
    });
  }
}
