/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Urgency as PrismaUrgency } from "@prisma/client";

export class UrgencyServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.UrgencyCountArgs, "select">): Promise<number> {
    return this.prisma.urgency.count(args);
  }

  async urgencies(args: Prisma.UrgencyFindManyArgs): Promise<PrismaUrgency[]> {
    return this.prisma.urgency.findMany(args);
  }
  async urgency(
    args: Prisma.UrgencyFindUniqueArgs
  ): Promise<PrismaUrgency | null> {
    return this.prisma.urgency.findUnique(args);
  }
  async createUrgency(args: Prisma.UrgencyCreateArgs): Promise<PrismaUrgency> {
    return this.prisma.urgency.create(args);
  }
  async updateUrgency(args: Prisma.UrgencyUpdateArgs): Promise<PrismaUrgency> {
    return this.prisma.urgency.update(args);
  }
  async deleteUrgency(args: Prisma.UrgencyDeleteArgs): Promise<PrismaUrgency> {
    return this.prisma.urgency.delete(args);
  }
}
