/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Urgency } from "./Urgency";
import { UrgencyCountArgs } from "./UrgencyCountArgs";
import { UrgencyFindManyArgs } from "./UrgencyFindManyArgs";
import { UrgencyFindUniqueArgs } from "./UrgencyFindUniqueArgs";
import { DeleteUrgencyArgs } from "./DeleteUrgencyArgs";
import { UrgencyService } from "../urgency.service";
@graphql.Resolver(() => Urgency)
export class UrgencyResolverBase {
  constructor(protected readonly service: UrgencyService) {}

  async _urgenciesMeta(
    @graphql.Args() args: UrgencyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Urgency])
  async urgencies(
    @graphql.Args() args: UrgencyFindManyArgs
  ): Promise<Urgency[]> {
    return this.service.urgencies(args);
  }

  @graphql.Query(() => Urgency, { nullable: true })
  async urgency(
    @graphql.Args() args: UrgencyFindUniqueArgs
  ): Promise<Urgency | null> {
    const result = await this.service.urgency(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Urgency)
  async deleteUrgency(
    @graphql.Args() args: DeleteUrgencyArgs
  ): Promise<Urgency | null> {
    try {
      return await this.service.deleteUrgency(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
