/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UrgencyService } from "../urgency.service";
import { UrgencyCreateInput } from "./UrgencyCreateInput";
import { Urgency } from "./Urgency";
import { UrgencyFindManyArgs } from "./UrgencyFindManyArgs";
import { UrgencyWhereUniqueInput } from "./UrgencyWhereUniqueInput";
import { UrgencyUpdateInput } from "./UrgencyUpdateInput";

export class UrgencyControllerBase {
  constructor(protected readonly service: UrgencyService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Urgency })
  async createUrgency(
    @common.Body() data: UrgencyCreateInput
  ): Promise<Urgency> {
    return await this.service.createUrgency({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Urgency] })
  @ApiNestedQuery(UrgencyFindManyArgs)
  async urgencies(@common.Req() request: Request): Promise<Urgency[]> {
    const args = plainToClass(UrgencyFindManyArgs, request.query);
    return this.service.urgencies({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Urgency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async urgency(
    @common.Param() params: UrgencyWhereUniqueInput
  ): Promise<Urgency | null> {
    const result = await this.service.urgency({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Urgency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUrgency(
    @common.Param() params: UrgencyWhereUniqueInput,
    @common.Body() data: UrgencyUpdateInput
  ): Promise<Urgency | null> {
    try {
      return await this.service.updateUrgency({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Urgency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUrgency(
    @common.Param() params: UrgencyWhereUniqueInput
  ): Promise<Urgency | null> {
    try {
      return await this.service.deleteUrgency({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
