/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Importance } from "./Importance";
import { ImportanceCountArgs } from "./ImportanceCountArgs";
import { ImportanceFindManyArgs } from "./ImportanceFindManyArgs";
import { ImportanceFindUniqueArgs } from "./ImportanceFindUniqueArgs";
import { DeleteImportanceArgs } from "./DeleteImportanceArgs";
import { ImportanceService } from "../importance.service";
@graphql.Resolver(() => Importance)
export class ImportanceResolverBase {
  constructor(protected readonly service: ImportanceService) {}

  async _importancesMeta(
    @graphql.Args() args: ImportanceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Importance])
  async importances(
    @graphql.Args() args: ImportanceFindManyArgs
  ): Promise<Importance[]> {
    return this.service.importances(args);
  }

  @graphql.Query(() => Importance, { nullable: true })
  async importance(
    @graphql.Args() args: ImportanceFindUniqueArgs
  ): Promise<Importance | null> {
    const result = await this.service.importance(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Importance)
  async deleteImportance(
    @graphql.Args() args: DeleteImportanceArgs
  ): Promise<Importance | null> {
    try {
      return await this.service.deleteImportance(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
