/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ImportanceService } from "../importance.service";
import { ImportanceCreateInput } from "./ImportanceCreateInput";
import { Importance } from "./Importance";
import { ImportanceFindManyArgs } from "./ImportanceFindManyArgs";
import { ImportanceWhereUniqueInput } from "./ImportanceWhereUniqueInput";
import { ImportanceUpdateInput } from "./ImportanceUpdateInput";

export class ImportanceControllerBase {
  constructor(protected readonly service: ImportanceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Importance })
  async createImportance(
    @common.Body() data: ImportanceCreateInput
  ): Promise<Importance> {
    return await this.service.createImportance({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Importance] })
  @ApiNestedQuery(ImportanceFindManyArgs)
  async importances(@common.Req() request: Request): Promise<Importance[]> {
    const args = plainToClass(ImportanceFindManyArgs, request.query);
    return this.service.importances({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Importance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async importance(
    @common.Param() params: ImportanceWhereUniqueInput
  ): Promise<Importance | null> {
    const result = await this.service.importance({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Importance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateImportance(
    @common.Param() params: ImportanceWhereUniqueInput,
    @common.Body() data: ImportanceUpdateInput
  ): Promise<Importance | null> {
    try {
      return await this.service.updateImportance({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Importance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteImportance(
    @common.Param() params: ImportanceWhereUniqueInput
  ): Promise<Importance | null> {
    try {
      return await this.service.deleteImportance({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
