/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Importance as PrismaImportance } from "@prisma/client";

export class ImportanceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ImportanceCountArgs, "select">
  ): Promise<number> {
    return this.prisma.importance.count(args);
  }

  async importances(
    args: Prisma.ImportanceFindManyArgs
  ): Promise<PrismaImportance[]> {
    return this.prisma.importance.findMany(args);
  }
  async importance(
    args: Prisma.ImportanceFindUniqueArgs
  ): Promise<PrismaImportance | null> {
    return this.prisma.importance.findUnique(args);
  }
  async createImportance(
    args: Prisma.ImportanceCreateArgs
  ): Promise<PrismaImportance> {
    return this.prisma.importance.create(args);
  }
  async updateImportance(
    args: Prisma.ImportanceUpdateArgs
  ): Promise<PrismaImportance> {
    return this.prisma.importance.update(args);
  }
  async deleteImportance(
    args: Prisma.ImportanceDeleteArgs
  ): Promise<PrismaImportance> {
    return this.prisma.importance.delete(args);
  }
}
