/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PurchasePrice } from "./PurchasePrice";
import { PurchasePriceCountArgs } from "./PurchasePriceCountArgs";
import { PurchasePriceFindManyArgs } from "./PurchasePriceFindManyArgs";
import { PurchasePriceFindUniqueArgs } from "./PurchasePriceFindUniqueArgs";
import { CreatePurchasePriceArgs } from "./CreatePurchasePriceArgs";
import { UpdatePurchasePriceArgs } from "./UpdatePurchasePriceArgs";
import { DeletePurchasePriceArgs } from "./DeletePurchasePriceArgs";
import { PurchasePriceService } from "../purchasePrice.service";
@graphql.Resolver(() => PurchasePrice)
export class PurchasePriceResolverBase {
  constructor(protected readonly service: PurchasePriceService) {}

  async _purchasePricesMeta(
    @graphql.Args() args: PurchasePriceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PurchasePrice])
  async purchasePrices(
    @graphql.Args() args: PurchasePriceFindManyArgs
  ): Promise<PurchasePrice[]> {
    return this.service.purchasePrices(args);
  }

  @graphql.Query(() => PurchasePrice, { nullable: true })
  async purchasePrice(
    @graphql.Args() args: PurchasePriceFindUniqueArgs
  ): Promise<PurchasePrice | null> {
    const result = await this.service.purchasePrice(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PurchasePrice)
  async createPurchasePrice(
    @graphql.Args() args: CreatePurchasePriceArgs
  ): Promise<PurchasePrice> {
    return await this.service.createPurchasePrice({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => PurchasePrice)
  async updatePurchasePrice(
    @graphql.Args() args: UpdatePurchasePriceArgs
  ): Promise<PurchasePrice | null> {
    try {
      return await this.service.updatePurchasePrice({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PurchasePrice)
  async deletePurchasePrice(
    @graphql.Args() args: DeletePurchasePriceArgs
  ): Promise<PurchasePrice | null> {
    try {
      return await this.service.deletePurchasePrice(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
