/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  PurchasePrice as PrismaPurchasePrice,
  Tenant as PrismaTenant,
} from "@prisma/client";

export class PurchasePriceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PurchasePriceCountArgs, "select">
  ): Promise<number> {
    return this.prisma.purchasePrice.count(args);
  }

  async purchasePrices(
    args: Prisma.PurchasePriceFindManyArgs
  ): Promise<PrismaPurchasePrice[]> {
    return this.prisma.purchasePrice.findMany(args);
  }
  async purchasePrice(
    args: Prisma.PurchasePriceFindUniqueArgs
  ): Promise<PrismaPurchasePrice | null> {
    return this.prisma.purchasePrice.findUnique(args);
  }
  async createPurchasePrice(
    args: Prisma.PurchasePriceCreateArgs
  ): Promise<PrismaPurchasePrice> {
    return this.prisma.purchasePrice.create(args);
  }
  async updatePurchasePrice(
    args: Prisma.PurchasePriceUpdateArgs
  ): Promise<PrismaPurchasePrice> {
    return this.prisma.purchasePrice.update(args);
  }
  async deletePurchasePrice(
    args: Prisma.PurchasePriceDeleteArgs
  ): Promise<PrismaPurchasePrice> {
    return this.prisma.purchasePrice.delete(args);
  }

  async getTenant(parentId: string): Promise<PrismaTenant | null> {
    return this.prisma.purchasePrice
      .findUnique({
        where: { id: parentId },
      })
      .tenant();
  }
}
