/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PurchasePriceService } from "../purchasePrice.service";
import { PurchasePriceCreateInput } from "./PurchasePriceCreateInput";
import { PurchasePrice } from "./PurchasePrice";
import { PurchasePriceFindManyArgs } from "./PurchasePriceFindManyArgs";
import { PurchasePriceWhereUniqueInput } from "./PurchasePriceWhereUniqueInput";
import { PurchasePriceUpdateInput } from "./PurchasePriceUpdateInput";

export class PurchasePriceControllerBase {
  constructor(protected readonly service: PurchasePriceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PurchasePrice })
  async createPurchasePrice(
    @common.Body() data: PurchasePriceCreateInput
  ): Promise<PurchasePrice> {
    return await this.service.createPurchasePrice({
      data: {
        ...data,

        tenant: data.tenant
          ? {
              connect: data.tenant,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        ownerId: true,
        productId: true,

        tenant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PurchasePrice] })
  @ApiNestedQuery(PurchasePriceFindManyArgs)
  async purchasePrices(
    @common.Req() request: Request
  ): Promise<PurchasePrice[]> {
    const args = plainToClass(PurchasePriceFindManyArgs, request.query);
    return this.service.purchasePrices({
      ...args,
      select: {
        createdAt: true,
        id: true,
        ownerId: true,
        productId: true,

        tenant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PurchasePrice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async purchasePrice(
    @common.Param() params: PurchasePriceWhereUniqueInput
  ): Promise<PurchasePrice | null> {
    const result = await this.service.purchasePrice({
      where: params,
      select: {
        createdAt: true,
        id: true,
        ownerId: true,
        productId: true,

        tenant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PurchasePrice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePurchasePrice(
    @common.Param() params: PurchasePriceWhereUniqueInput,
    @common.Body() data: PurchasePriceUpdateInput
  ): Promise<PurchasePrice | null> {
    try {
      return await this.service.updatePurchasePrice({
        where: params,
        data: {
          ...data,

          tenant: data.tenant
            ? {
                connect: data.tenant,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          ownerId: true,
          productId: true,

          tenant: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PurchasePrice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePurchasePrice(
    @common.Param() params: PurchasePriceWhereUniqueInput
  ): Promise<PurchasePrice | null> {
    try {
      return await this.service.deletePurchasePrice({
        where: params,
        select: {
          createdAt: true,
          id: true,
          ownerId: true,
          productId: true,

          tenant: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
